In [1]:
import tensorflow as tf
from tensorflow import keras
from functools import partial
import os, json, jsonpickle
import numpy as np
import cv2
from PIL import Image
from csv_creator import make_csv
from tfrecord_creator import create_tfrecords
from tfrecord_parser import parse_tfrecords

In [2]:
# make_csv(train_images_dir='../../mask_data/coco/val2017/',
#     train_anno_dir='../../mask_data/coco/annotations/instances_val2017.json',
#     annotation_format='coco',
#     split=0.5)

In [3]:
# create_tfrecords('/tmp/dataset.json','/tmp/dataset.csv')

In [4]:
dataset = parse_tfrecords(
        filenames='/tmp/*.tfrecord', 
        batch_size=2,
        num_classes=5)

(None, None, None) FixedLenFeature(shape=[], dtype=tf.int64, default_value=None) FixedLenFeature(shape=[], dtype=tf.int64, default_value=None)


In [5]:
for data, annotation in dataset.take(10):
    image_batch = data.numpy()
    ann = annotation['label_batch'].numpy()
    print(ann)
    print(image_batch.shape)

[[21 49 53]
 [20 -1 -1]]
(2, 500, 500, 3)
[[49 33 -1 -1 -1 -1 -1 -1 -1]
 [13 49 49 49 49 49 49 49 49]]
(2, 640, 640, 3)
[[20 -1]
 [49 33]]
(2, 480, 640, 3)
[[21 49 53 -1 -1 -1 -1 -1 -1]
 [13 49 49 49 49 49 49 49 49]]
(2, 640, 554, 3)
[[21 49 53]
 [49 33 -1]]
(2, 500, 640, 3)
[[20 -1 -1 -1 -1 -1 -1 -1 -1]
 [13 49 49 49 49 49 49 49 49]]
(2, 640, 554, 3)
[[49 33 -1]
 [21 49 53]]
(2, 500, 640, 3)
[[20 -1]
 [49 33]]
(2, 480, 640, 3)
[[20 -1 -1]
 [21 49 53]]
(2, 500, 500, 3)
[[20 -1 -1]
 [21 49 53]]
(2, 500, 500, 3)
